// central hook interface between source engine and source mod
// here are all hook invocations broadcasted to each extension

class CTakeDamageInfo;

#include "glue.hpp"

SourcemodRouter<fastdelegate::FastDelegate0<>, IServerGameDLL> g_SMGlue_IServerGameDLL__GameServerSteamAPIActivated;
SourcemodRouter<fastdelegate::FastDelegate0<>, IServerGameDLL> g_SMGlue_IServerGameDLL__LevelShutdown;
SourcemodRouter<fastdelegate::FastDelegate0<>, IVEngineServer> g_SMGlue_IVEngineServer__MessageEnd;
SourcemodRouter<fastdelegate::FastDelegate0<const char *>, IServerGameDLL> g_SMGlue_IServerGameDLL__GetGameDescription;
SourcemodRouter<fastdelegate::FastDelegate0<const char *>, IVEngineServer> g_SMGlue_IVEngineServer__GetMapEntitiesString;
SourcemodRouter<fastdelegate::FastDelegate15<IRecipientFilter &, int, int, const char *, float, soundlevel_t, int, int, int, const Vector *, const Vector *, CUtlVector<Vector> *, bool, float, int, void>, IEngineSound> g_SMGlue_IEngineSound__EmitSound;
SourcemodRouter<fastdelegate::FastDelegate15<IRecipientFilter &, int , int , const char *, float , float , int , int , int , const Vector *, const Vector *, CUtlVector<Vector> *, bool , float , int>, IEngineSound> g_SMGlue_IEngineSound__EmitSound2;
SourcemodRouter<fastdelegate::FastDelegate1<ConCommandBase *>, ICvar> g_SMGlue_ICvar__UnregisterConCommand;
SourcemodRouter<fastdelegate::FastDelegate1<bool>, IServerGameDLL> g_SMGlue_IServerGameDLL__ServerHibernationUpdate;
SourcemodRouter<fastdelegate::FastDelegate1<bool>, IServerGameDLL> g_SMGlue_IServerGameDLL__SetServerHibernation;
SourcemodRouter<fastdelegate::FastDelegate1<bool>, IServerGameDLL> g_SMGlue_IServerGameDLL__Think;
SourcemodRouter<fastdelegate::FastDelegate1<const CCommand &>, ConCommand> g_SMGlue_ConCommand__Dispatch;
SourcemodRouter<fastdelegate::FastDelegate1<const char *>, IVEngineServer> g_SMGlue_IVEngineServer__LogPrint;
SourcemodRouter<fastdelegate::FastDelegate1<edict_t *>, IServerGameClients> g_SMGlue_IServerGameClients__ClientDisconnect;
SourcemodRouter<fastdelegate::FastDelegate1<edict_t *>, IServerGameClients> g_SMGlue_IServerGameClients__ClientSettingsChanged;
SourcemodRouter<fastdelegate::FastDelegate1<edict_t *>, IServerGameClients> g_SMGlue_IServerGameClients__ClientVoice;
SourcemodRouter<fastdelegate::FastDelegate1<int>, IServerGameClients> g_SMGlue_IServerGameClients__SetCommandClient;
SourcemodRouter<fastdelegate::FastDelegate2<ConCommandBase *, bool>, ICvar> g_SMGlue_ICvar__RegisterConCommand;
SourcemodRouter<fastdelegate::FastDelegate2<ConVar *, const char *>, ICvar> g_SMGlue_ICvar__CallGlobalChangeCallback;
SourcemodRouter<fastdelegate::FastDelegate2<IGameEvent *, bool, bool>, IGameEventManager2> g_SMGlue_IGameEventManager2__FireEvent;
SourcemodRouter<fastdelegate::FastDelegate2<bool, bool>, IServerGameDLL> g_SMGlue_IServerGameDLL__GameFrame;
SourcemodRouter<fastdelegate::FastDelegate2<const char *, const char *>, IVEngineServer> g_SMGlue_IVEngineServer__ChangeLevel;
SourcemodRouter<fastdelegate::FastDelegate2<edict_t *, KeyValues *>, IServerGameClients> g_SMGlue_IServerGameClients__ClientCommandKeyValues;
SourcemodRouter<fastdelegate::FastDelegate2<edict_t *, const CCommand &>, IServerGameClients> g_SMGlue_IServerGameClients__ClientCommand;
SourcemodRouter<fastdelegate::FastDelegate2<edict_t *, const char*>, IVEngineServer> g_SMGlue_IVEngineServer__ClientCommand;
SourcemodRouter<fastdelegate::FastDelegate2<edict_t *, const char *>, IServerGameClients> g_SMGlue_IServerGameClients__ClientPutInServer;
SourcemodRouter<fastdelegate::FastDelegate2<edict_t *, const char *>, IVEngineServer> g_SMGlue_IVEngineServer__ClientPrintf;
SourcemodRouter<fastdelegate::FastDelegate3<ConVar *, const char *, float>, ICvar> g_SMGlue_ICvar__CallGlobalChangeCallbacks;
SourcemodRouter<fastdelegate::FastDelegate3<bf_write *, IRecipientFilter *, int, const char *>, IVEngineServer> g_SMGlue_IVEngineServer__UserMessageBegin;
SourcemodRouter<fastdelegate::FastDelegate3<int, int, bool, bool>, IVoiceServer> g_SMGlue_IVoiceServer__SetClientListening;
SourcemodRouter<fastdelegate::FastDelegate3<edict_t *, int, int>, IServerGameDLL> g_SMGlue_IServerGameDLL__ServerActivate;
SourcemodRouter<fastdelegate::FastDelegate4<edict_t *, DIALOG_TYPE, KeyValues *, IServerPluginCallbacks *>, IServerPluginHelpers> g_SMGlue_IServerPluginHelpers__CreateMessage;
SourcemodRouter<fastdelegate::FastDelegate5<IRecipientFilter &, float, const void *, const SendTable *, int>, IVEngineServer> g_SMGlue_IVEngineServer__PlaybackTempEntity;
SourcemodRouter<fastdelegate::FastDelegate5<QueryCvarCookie_t, edict_t *, EQueryCvarValueStatus, const char *, const char *>, IServerGameDLL> g_SMGlue_IServerGameDLL__OnQueryCvarValueFinished;
SourcemodRouter<fastdelegate::FastDelegate5<QueryCvarCookie_t, edict_t *, EQueryCvarValueStatus, const char *, const char *>, IServerPluginCallbacks> g_SMGlue_IServerPluginCallbacks__OnQueryCvarValueFinished;
SourcemodRouter<fastdelegate::FastDelegate5<edict_t *, const char *, const char *, char *, int, bool>, IServerGameClients> g_SMGlue_IServerGameClients__ClientConnect;
SourcemodRouter<fastdelegate::FastDelegate6<const char *, const char *, const char *, const char *, bool, bool, bool>, IServerGameDLL> g_SMGlue_IServerGameDLL__LevelInit;
SourcemodRouter<fastdelegate::FastDelegate8<int, const Vector &, const char *, float, soundlevel_t, int, int, float>, IVEngineServer> g_SMGlue_IVEngineServer__EmitAmbientSound;
SourcemodRouter<fastdelegate::FastDelegate0<bool>, CBaseEntity> g_SMGlue_P0__CanBeAutobalanced;
SourcemodRouter<fastdelegate::FastDelegate0<bool>, CBaseEntity> g_SMGlue_P0__Reload;
SourcemodRouter<fastdelegate::FastDelegate0<bool>, IServerGameDLL> g_SMGlue_P0__SGD_GameInit;
SourcemodRouter<fastdelegate::FastDelegate0<int>, CBaseEntity> g_SMGlue_P0__GetMaxHealth;
SourcemodRouter<fastdelegate::FastDelegate0<void>, CBaseEntity> g_SMGlue_P0__PostThink;
SourcemodRouter<fastdelegate::FastDelegate0<void>, CBaseEntity> g_SMGlue_P0__PreThink;
SourcemodRouter<fastdelegate::FastDelegate0<void>, CBaseEntity> g_SMGlue_P0__Spawn;
SourcemodRouter<fastdelegate::FastDelegate0<void>, CBaseEntity> g_SMGlue_P0__Think;
SourcemodRouter<fastdelegate::FastDelegate0<void>, IServerGameDLL> g_SMGlue_P0__SGD_LevelShutdown;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseCombatWeapon *, bool>, CBaseEntity> g_SMGlue_P1__Weapon_CanSwitchTo;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseCombatWeapon *, bool>, CBaseEntity> g_SMGlue_P1__Weapon_CanUse;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseCombatWeapon *, void>, CBaseEntity> g_SMGlue_P1__Weapon_Equip;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseEntity *, void>, CBaseEntity> g_SMGlue_P1__Blocked;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseEntity *, void>, CBaseEntity> g_SMGlue_P1__EndTouch;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseEntity *, void>, CBaseEntity> g_SMGlue_P1__StartTouch;
SourcemodRouter<fastdelegate::FastDelegate1<CBaseEntity *, void>, CBaseEntity> g_SMGlue_P1__Touch;
SourcemodRouter<fastdelegate::FastDelegate1<CTakeDamageInfo&, int>, CBaseEntity> g_SMGlue_P1__OnTakeDamage;
SourcemodRouter<fastdelegate::FastDelegate1<CTakeDamageInfo&, int>, CBaseEntity> g_SMGlue_P1__OnTakeDamage_Alive;
SourcemodRouter<fastdelegate::FastDelegate1<FireBulletsInfo_t const&, void>, CBaseEntity> g_SMGlue_P1__FireBullets;
SourcemodRouter<fastdelegate::FastDelegate1<IPhysicsObject *, void>, CBaseEntity> g_SMGlue_P1__VPhysicsUpdate;
SourcemodRouter<fastdelegate::FastDelegate1<void *, void>, CBaseEntity> g_SMGlue_P1__GroundEntChanged;
SourcemodRouter<fastdelegate::FastDelegate2<CBaseCombatWeapon *, int, bool>, CBaseEntity> g_SMGlue_P2__Weapon_Switch;
SourcemodRouter<fastdelegate::FastDelegate2<CCheckTransmitInfo *, bool, void>, CBaseEntity> g_SMGlue_P2__SetTransmit;
SourcemodRouter<fastdelegate::FastDelegate2<CUserCmd *, IMoveHelper *, void>, CUserCmd> g_SMGlue_P2__PlayerRunCmdHook;
SourcemodRouter<fastdelegate::FastDelegate2<int, int, bool>, CBaseEntity> g_SMGlue_P2__ShouldCollide;
SourcemodRouter<fastdelegate::FastDelegate3<CBaseCombatWeapon *, const Vector *, const Vector *, void>, CBaseEntity> g_SMGlue_P3__Weapon_Drop;
SourcemodRouter<fastdelegate::FastDelegate3<CTakeDamageInfo&, const Vector &, CGameTrace *, void>, CBaseEntity> g_SMGlue_P3__TraceAttack;
SourcemodRouter<fastdelegate::FastDelegate4<CBaseEntity *, CBaseEntity *, USE_TYPE, float, void>, CBaseEntity> g_SMGlue_P4__Use;
SourcemodRouter<fastdelegate::FastDelegate4<CTakeDamageInfo&, const Vector &, CGameTrace *, CDmgAccumulator *, void>, CBaseEntity> g_SMGlue_P4__TraceAttack;
SourcemodRouter<fastdelegate::FastDelegate6<const char *, const char *, const char *, const char *, bool, bool, bool>, IServerGameDLL> g_SMGlue_P6__SGD_LevelInit;
SourcemodRouter<fastdelegate::FastDelegate2<const char*, const char*, bool>, IBaseFileSystem> g_SMGlue_IBaseFileSystem__FileExists;
SourcemodRouter<fastdelegate::FastDelegate2<const char*, unsigned int, bool>, INetChannel> g_SMGlue_INetChannel__SendFile;
SourcemodRouter<fastdelegate::FastDelegate2<struct netpacket_s*, bool>, INetChannel> g_SMGlue_INetChannel__ProcessPacket;
SourcemodRouter<fastdelegate::FastDelegate1<CLC_VoiceData*, bool>, IClientMessageHandler> g_SMGlue_IClientMessageHandler__ProcessVoiceData;
SourcemodRouter<fastdelegate::FastDelegate2<CUserCmd *, IMoveHelper *, void>, CBaseEntity> g_SMGlue_P2__PlayerRunCmdHook2;