#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'cdetour'


def options(opt):
	# stub
	pass

def configure(conf):
	#conf.define('fopen','dont_use_fopen') # WINDOWS
	conf.env.append_unique('DEFINES',[
		'SE_BLOODYGOODTIME=4',
		'SE_EYE=5',
		'SE_EPISODEONE=1',
		'SE_DEADLOCK=27',
		'SE_DARKMESSIAH=2',
		'SE_NUCLEARDAWN=14',
		'SE_CONTAGION=15',
		'SE_CS2=25',
		'SE_DOTA=24',
		'SE_PORTAL2=18',
		'SE_DOI=21',
		'SE_PVKII=10',
		'SE_DODS=8',
		'SE_BMS=11',
		'SE_ALIENSWARM=17',
		'SE_BLADE=19',
		'SE_ORANGEBOX=3',
		'SE_TF2=12',
		'SE_SDK2013=9',
		'SE_INSURGENCY=20',
		'SE_CSGO=23',
		'SE_MCV=22',
		'SE_HL2DM=7',
		'SE_LEFT4DEAD=13',
		'SE_LEFT4DEAD2=16',
		'SE_MOCK=26',
		'SE_CSS=6',
		'SOURCE_ENGINE_PVKII=27',
		'SOURCE_ENGINE=6',
		'V_snprintf=_snprintf',
	])
	pass

def build(bld):
	source = ['detours.cpp']
	
	includes = [
		'.',
		'..',
		'../sourcepawn/include',
		'../metamod/core',
		'../metamod/core/sourcehook',
		'../../public',
		'../../public/engine',
		'../../public/mathlib',
		'../../public/game/server',
		'../../public/sourcemod',
		'../../public/sourcemod/extensions',
		'../../public/sourcemod/safetyhook',
		'../../public/sourcemod/safetyhook/include',
		'../../public/sourcemod/amtl',
		'../../public/sourcemod/amtl/amtl',
		'../../public/sourcemod/amtl/include',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/steam',
		'../../game/shared'
	]

	defines = []

	libs = ['tier0','tier1','tier2','tier3','vstdlib', 'mathlib', 'logic', 'core', 'sourcemod/logic']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

