#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'sourcemodsqlite'

import sys
sys.path.append("..")
from sourcemod_config import build_vars, configure_vars
sys.path.append(f"./{PROJECT_NAME.replace('sourcemod', 'sourcemod_')}")


def options(opt):
	# stub
	pass

def configure(conf):
	configure_vars(conf, PROJECT_NAME) # Todo specify Windows

def build(bld):
	source = [

		'extension.cpp',
		'driver/SqDatabase.cpp',
		'driver/SqDriver.cpp',
		'driver/SqQuery.cpp',
		'driver/SqResults.cpp',
		'sqlite3.c',
		'../public/sourcemod/smsdk_ext.cpp'

	]
	includes, defines, libs = [], [], []
	build_vars(bld, includes, defines, libs, PROJECT_NAME) # Todo specify Windows

	install_path = None if bld.env.BUILD_SDK else bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

