#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'sourcemodlogic'

import sys
sys.path.append("..")
from sourcemod_config import build_vars, configure_vars
sys.path.append(f"./{PROJECT_NAME.replace('sourcemod', 'sourcemod_')}")



def options(opt):
	# stub
	pass

def configure(conf):
	configure_vars(conf, PROJECT_NAME) # Todo specify Windows

def build(bld):
	source = [
		'AdminCache.cpp',
		'ADTFactory.cpp',
		'BaseWorker.cpp',
		'CDataPack.cpp',
		'common_logic.cpp',
		'Database.cpp',
		'DatabaseConfBuilder.cpp',
		'DebugReporter.cpp',
		'ExtensionSys.cpp',
		'ForwardSys.cpp',
		'frame_tasks.cpp',
		'FrameIterator.cpp',
		'GameConfigs.cpp',
		'HandleSys.cpp',
		'LibrarySys.cpp',
		'Logger.cpp',
		'LumpManager.cpp',
		'MemoryUtils.cpp',
		'NativeOwner.cpp',
		'PhraseCollection.cpp',
		'PluginSys.cpp',
		'ProfileTools.cpp',
		'PseudoAddrManager.cpp',
		'RootConsoleMenu.cpp',
		'ShareSys.cpp',
		'sm_crc32.cpp',
		'sm_trie.cpp',
		'smn_admin.cpp',
		'smn_adt_array.cpp',
		'smn_adt_stack.cpp',
		'smn_adt_trie.cpp',
		'smn_banning.cpp',
		'smn_console.cpp',
		'smn_core.cpp',
		'smn_database.cpp',
		'smn_datapacks.cpp',
		'smn_entitylump.cpp',
		'smn_fakenatives.cpp',
		'smn_filesystem.cpp',
		'smn_float.cpp',
		'smn_functions.cpp',
		'smn_gameconfigs.cpp',
		'smn_halflife.cpp',
		'smn_handles.cpp',
		'smn_lang.cpp',
		'smn_maplists.cpp',
		'smn_menus.cpp',
		'smn_players.cpp',
		'smn_profiler.cpp',
		'smn_sorting.cpp',
		'smn_string.cpp',
		'smn_textparse.cpp',
		'smn_timers.cpp',
		'sprintf.cpp',
		'stringutil.cpp',
		'TextParsers.cpp',
		'ThreadSupport.cpp',
		'Translator.cpp',
	]

	includes, defines, libs = [], [], []
	build_vars(bld, includes, defines, libs, PROJECT_NAME) # Todo specify Windows

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		cflags   = ['-fvisibility=default'], 
		cxxflags = ['-fvisibility=default'], 
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

