#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'sourcemodmetamodcore'

import sys
sys.path.append("..")
from sourcemod_config import build_vars, configure_vars
sys.path.append(f"./{PROJECT_NAME.replace('sourcemod', 'sourcemod_')}")


def options(opt):
	# stub
	pass

def configure(conf):
	configure_vars(conf, PROJECT_NAME) # Todo specify Windows

def build(bld):
	source = [

		'metamod.cpp',
		'metamod_console.cpp',
		'metamod_oslink.cpp',
		'metamod_plugins.cpp',
		'metamod_util.cpp',
		'provider/console.cpp',
		'provider/provider_ep2.cpp',
		'sourcehook/sourcehook.cpp',
		'sourcehook/sourcehook_hookmangen.cpp',
		'sourcehook/sourcehook_impl_chookidman.cpp',
		'sourcehook/sourcehook_impl_chookmaninfo.cpp',
		'sourcehook/sourcehook_impl_cproto.cpp',
		'sourcehook/sourcehook_impl_cvfnptr.cpp',
		'gamedll_bridge.cpp',
		'vsp_bridge.cpp',

	]

	includes, defines, libs = [], [], []
	build_vars(bld, includes, defines, libs, PROJECT_NAME) # Todo specify Windows

	install_path = None if bld.env.BUILD_SDK else bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count(),
		cflags       = ['-fvisibility=default'], 
		cxxflags     = ['-fvisibility=default'], 
	)

